version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.8
    ports:
        - 3310:3306
    environment:
        MARIADB_USER: tester
        MARIADB_PASSWORD: testerpassword
    restart: always
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    command:
      - php bin/console regenerate-app-secret
      - php bin/console doctrine:database:create
      - php bin/console doctrine:migrations:migrate