version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin54321#L
      MYSQL_DATABASE: shop
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin54321
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    command: >
      bash -c "
      php bin/console doctrine:database:create --if-not-exists &&
      php bin/console doctrine:migrations:migrate --no-interaction
      "
    environment:
      DATABASE_URL: mysql://admin:admin54321@mariadb:3306/shop

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - php
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: mysql://admin:admin54321@mariadb:3306/shop

volumes:
  db_data: